linters-settings:
  lll:
    line-length: 140

  funlen:
    lines: 100
    statements: 50

  exhaustive:
    default-signifies-exhaustive: true

  revive:
    rules:
    - name: unused-parameter
      disabled: true

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused

  # don't enable:
  #  - whitespace
  #  - wsl
  # - deadcode
  # - depguard
  # - asciicheck
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - golint
  # - gomnd
  # - interfacer
  # - lll
  # - maligned
  # - nestif
  # - prealloc
  # - structcheck
  # - testpackage
  # - unparam
  # - varcheck

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - gomnd
        - gosec
        - revive